import React, {useEffect, useRef, useState} from 'react';
import {API_BASE, get, IngestFile} from '../lib/api';

export default function IngestData({notify,setPage}:{notify:(message:string)=>void;setPage:(page:string)=>void}) {
 const [file,setFile]=useState<File>(); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [history,setHistory]=useState<IngestFile[]>([]); const input=useRef<HTMLInputElement>(null);
 const load=()=>get<IngestFile[]>('v1/ingest/files').then(setHistory).catch(()=>setHistory([])); useEffect(()=>{ void load(); },[]);
 const upload=async()=>{if(!file)return; setBusy(true);setMessage('');try {const form=new FormData();form.append('file',file);const r=await fetch(`${API_BASE}/v1/ingest/files`,{method:'POST',body:form});const data=await r.json();if(!r.ok)throw Error(data.detail||'Upload failed');setMessage(`${data.status}: ${data.lot_id||file.name} · ${data.devices||0} devices · ${data.results||0} test results`);notify('File ingested. Analytics refreshed.');load();setPage('Mission Control');}catch(e:any){setMessage(`Upload failed: ${e.message}`)}finally{setBusy(false)}};
 return <><header><div><p className="eyebrow">DATA ACQUISITION / TRACEABLE INGEST</p><h1>Ingest Test Data</h1><p className="muted">Upload STDF V4, ATDF, compressed tester output, or a canonical semiconductor CSV.</p></div></header><section className="panel"><div className="upload-zone" onClick={()=>input.current?.click()}><input ref={input} type="file" accept=".stdf,.std,.atdf,.csv,.gz,.zip,.tgz,.tar.gz" hidden onChange={e=>setFile(e.target.files?.[0])}/><div className="upload-icon">⇧</div><h2>{file?file.name:'Choose test-data file'}</h2><p>STDF V4 · ATDF · CSV · GZ · ZIP · TAR.GZ</p><button className="primary" type="button">Browse files</button></div>{file&&<div className="upload-actions"><div><b>{file.name}</b><small>{(file.size/1024).toFixed(1)} KB</small></div><button className="primary" disabled={busy} onClick={upload}>{busy?'Ingesting…':'Validate & Ingest'}</button></div>}{message&&<p className={message.startsWith('Upload failed')?'bad':'ok'}>{message}</p>}</section><section className="panel"><h2>CSV profile</h2><p className="muted">CSV is supported when it has a header row with: <code>wafer_id, x_coord, y_coord, passed</code>. Optional columns include <code>lot_id, device_id, site, hardware_bin, test_num, test_name, measured_value, lower_limit, upper_limit, unit, pin_name, retest_count</code>.</p><p className="muted">Unknown CSV layouts are rejected with a mapping-required quality finding rather than producing misleading analytics.</p></section><section className="panel"><div className="head"><h2>Recent ingestion history</h2><button className="ghost" onClick={load}>Refresh</button></div><table className="data-table"><thead><tr><th>File</th><th>Format</th><th>Lot</th><th>Status</th><th>Records</th><th>Errors</th></tr></thead><tbody>{history.map(x=><tr key={x.file_id}><td>{x.file_name}</td><td>{x.source_format}</td><td>{x.lot_id}</td><td className={x.status==='validated'?'ok':'amber'}>{x.status}</td><td>{x.records_parsed}</td><td>{x.error_count}</td></tr>)}</tbody></table></section></>;
}
